CREATE TABLE "GCG_5009_MSC_MAINT"(
 "FILE_DIR" CHAR(500),
 "MAT_SEQ" BIT NOT NULL ,
 "MISC_SEQ" BIT NOT NULL ,
 "JOB_FORMAT" CHAR(50),
 "LOG_LENGTH" INTEGER,
 "HIST_LENGTH" INTEGER,
 "VENDOR" CHAR(6),
 "GL_ACCT" CHAR(15),
 "DUE_LEAD" INTEGER,
 "EMAIL" CHAR(500),
 "ID" IDENTITY DEFAULT '0',
 UNIQUE ("ID"));