CREATE TABLE "GCG_5009_ISSUE_LOG"(
 "PART_NO" CHAR(20),
 "PART_DESC" CHAR(30),
 "DATETIME" DATETIME,
 "USER_ID" CHAR(3),
 "JOB_NO" CHAR(6),
 "JOB_SUFFIX" CHAR(3),
 "JOB_SEQ" CHAR(6),
 "ISSUE_QTY" NUMERIC(15,6),
 "UNIT_COST" NUMERIC(16,6),
 "DATETIME_LOG" DATETIME,
 "FILE_LOG" CHAR(500),
  "ID" IDENTITY DEFAULT '0');